mklink %USERPROFILE%\.bashrc %USERPROFILE%\tools\config\.bashrc
mklink %USERPROFILE%\.gitconfig %USERPROFILE%\tools\config\.gitconfig
mklink %USERPROFILE%\.node-inspectorrc %USERPROFILE%\tools\config\.node-inspectorrc 
mklink %USERPROFILE%\.inputrc %USERPROFILE%\tools\config\.inputrc
mklink %USERPROFILE%\.jshintrc %USERPROFILE%\tools\config\.jshintrc
mklink %USERPROFILE%\.eslintrc.js %USERPROFILE%\tools\config\.eslintrc.js
mklink %USERPROFILE%\.npmrc %USERPROFILE%\tools\config\.npmrc
mklink %USERPROFILE%\.vimrc %USERPROFILE%\tools\vimrc\_vimrc
mklink %USERPROFILE%\.gvimrc %USERPROFILE%\tools\vimrc\_gvimrc
