mklink %USERPROFILE%\.bashrc %USERPROFILE%\tools\config\.bashrc
mklink %USERPROFILE%\.profile %USERPROFILE%\tools\config\.profile
mklink %USERPROFILE%\.gitconfig %USERPROFILE%\tools\config\.gitconfig
mklink %USERPROFILE%\.node-inspectorrc %USERPROFILE%\tools\config\.node-inspectorrc 
mklink %USERPROFILE%\.inputrc %USERPROFILE%\tools\config\.inputrc
mklink %USERPROFILE%\.jshintrc %USERPROFILE%\tools\config\.jshintrc
mklink %USERPROFILE%\.eslintrc.js %USERPROFILE%\tools\config\.eslintrc.js
mklink %USERPROFILE%\.tmux.conf %USERPROFILE%\tools\config\.tmux.conf
mklink %USERPROFILE%\.npmrc %USERPROFILE%\tools\config\.npmrc
mklink %USERPROFILE%\.vimrc %USERPROFILE%\tools\vimrc\_vimrc
mklink %USERPROFILE%\.gvimrc %USERPROFILE%\tools\vimrc\_gvimrc
mklink %USERPROFILE%\.vsvimrc %USERPROFILE%\tools\vimrc\_vsvimrc
mklink %USERPROFILE%\.ideavimrc %USERPROFILE%\tools\vimrc\_vsvimrc
